services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grand-central-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - grand-central-network

  backend:
    image: grand-central-backend:latest
    container_name: grand-central-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://grandcentral:password@host.docker.internal:5432/grand_central
      - REDIS_URL=redis://host.docker.internal:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - grand-central-network

networks:
  grand-central-network:
    driver: bridge