services:
  alibaba-sync:
    build:
      context: .
      dockerfile: Dockerfile.alibaba
    container_name: alibaba-message-sync
    restart: unless-stopped
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALIBABA_USERNAME=${ALIBABA_USERNAME}
      - ALIBABA_PASSWORD=${ALIBABA_PASSWORD}
      - BROWSER_HEADLESS=${BROWSER_HEADLESS:-true}
      - EMAIL_2FA_FOLDER=${EMAIL_2FA_FOLDER:-2FA}
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./archive:/app/archive
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"