import { Chat, Message, Platform, Profile } from '../types';

export const mockPlatforms: Platform[] = [
  {
    id: '1',
    name: 'alibaba',
    display_name: 'Alibaba',
    icon_url: '',
    is_active: true,
  },
  {
    id: '2',
    name: 'grindr',
    display_name: 'Grindr',
    icon_url: '',
    is_active: true,
  },
];

export const mockProfiles: Profile[] = [
  {
    id: '1',
    platform_id: '1',
    name: 'Linda Wu',
    username: 'linda.wu',
    avatar_url: '',
    bio: 'Supplier at Guangzhou Horae Industrial Co., Ltd.',
    location: 'Guangzhou, China',
    is_active: true,
  },
  {
    id: '2',
    platform_id: '1',
    name: 'Steven Huang',
    username: 'steven.huang',
    avatar_url: '',
    bio: 'Sales Manager at Yiwu Kaizhuo Trading Co., Ltd.',
    location: 'Yiwu, China',
    is_active: true,
  },
  {
    id: '3',
    platform_id: '2',
    name: 'Alex',
    username: 'alex_23',
    avatar_url: '',
    bio: 'Looking for fun',
    location: '2.1 miles away',
    is_active: true,
  },
];

export const mockMessages: { [chatId: string]: Message[] } = {
  'chat-1': [
    {
      id: 'msg-1',
      chat_id: 'chat-1',
      direction: 'INCOMING',
      content: 'Hi Daniel, we received your inquiry about the fabric samples. We can send them to you.',
      created_at: '2025-06-16T08:30:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
      sender_name: 'Linda Wu',
    },
    {
      id: 'msg-2',
      chat_id: 'chat-1',
      direction: 'OUTGOING',
      content: 'Great! How much would shipping cost to the US?',
      created_at: '2025-06-16T08:35:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
    },
    {
      id: 'msg-3',
      chat_id: 'chat-1',
      direction: 'INCOMING',
      content: 'For samples, shipping is usually $25-35 by DHL. We can ship within 2 business days.',
      created_at: '2025-06-16T08:40:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
      sender_name: 'Linda Wu',
    },
    {
      id: 'msg-4',
      chat_id: 'chat-1',
      direction: 'OUTGOING',
      content: 'Perfect! Please send me an invoice.',
      created_at: '2025-06-16T08:45:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
    },
    {
      id: 'msg-5',
      chat_id: 'chat-1',
      direction: 'INCOMING',
      content: 'ok, when we receive them, we will check and confirm with you :)',
      created_at: '2025-06-16T19:32:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
      sender_name: 'Linda Wu',
    },
  ],
  'chat-2': [
    {
      id: 'msg-6',
      chat_id: 'chat-2',
      direction: 'INCOMING',
      content: 'Hi Daniel, thank you for your order. We are preparing the shipment now.',
      created_at: '2025-06-15T14:20:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
      sender_name: 'Steven Huang',
    },
    {
      id: 'msg-7',
      chat_id: 'chat-2',
      direction: 'OUTGOING',
      content: 'Great! When do you expect to ship?',
      created_at: '2025-06-15T14:25:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
    },
    {
      id: 'msg-8',
      chat_id: 'chat-2',
      direction: 'INCOMING',
      content: 'rather than size S or M, please send 2 XXL, 1 orange and 1 red',
      created_at: '2025-06-15T21:30:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: true,
      reply_to_content: 'Great! When do you expect to ship?',
      sender_name: 'Steven Huang',
    },
    {
      id: 'msg-9',
      chat_id: 'chat-2',
      direction: 'OUTGOING',
      content: 'Okay.',
      created_at: '2025-06-15T21:35:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
    },
  ],
  'chat-3': [
    {
      id: 'msg-10',
      chat_id: 'chat-3',
      direction: 'INCOMING',
      content: 'Hey cutie 😉',
      created_at: '2025-06-16T22:10:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
      sender_name: 'Alex',
    },
    {
      id: 'msg-11',
      chat_id: 'chat-3',
      direction: 'OUTGOING',
      content: 'Hi there!',
      created_at: '2025-06-16T22:15:00Z',
      is_deleted: false,
      ai_generated: false,
      is_reply: false,
    },
  ],
};

export const mockChats: Chat[] = [
  {
    id: 'chat-1',
    account_id: 'account-1',
    profile_id: '1',
    platform_chat_id: 'chat_3_linda_wu',
    is_active: true,
    is_archived: false,
    is_starred: false,
    is_muted: false,
    unread_count: 1,
    last_message_at: '2025-06-16T19:32:00Z',
    created_at: '2025-06-15T08:00:00Z',
    updated_at: '2025-06-16T19:32:00Z',
    profile: mockProfiles[0],
    platform: mockPlatforms[0],
    last_message: mockMessages['chat-1'][mockMessages['chat-1'].length - 1],
  },
  {
    id: 'chat-2',
    account_id: 'account-1',
    profile_id: '2',
    platform_chat_id: 'chat_0_steven_huang',
    is_active: true,
    is_archived: false,
    is_starred: true,
    is_muted: false,
    unread_count: 0,
    last_message_at: '2025-06-15T21:35:00Z',
    created_at: '2025-06-15T10:00:00Z',
    updated_at: '2025-06-15T21:35:00Z',
    profile: mockProfiles[1],
    platform: mockPlatforms[0],
    last_message: mockMessages['chat-2'][mockMessages['chat-2'].length - 1],
  },
  {
    id: 'chat-3',
    account_id: 'account-2',
    profile_id: '3',
    platform_chat_id: 'grindr_alex_23',
    is_active: true,
    is_archived: false,
    is_starred: false,
    is_muted: false,
    unread_count: 0,
    last_message_at: '2025-06-16T22:15:00Z',
    created_at: '2025-06-16T22:00:00Z',
    updated_at: '2025-06-16T22:15:00Z',
    profile: mockProfiles[2],
    platform: mockPlatforms[1],
    last_message: mockMessages['chat-3'][mockMessages['chat-3'].length - 1],
  },
];